# Generated by Django 3.1.4 on 2021-01-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=30, unique=True)),
                ('lName', models.CharField(max_length=100)),
                ('mName', models.CharField(max_length=100)),
                ('fName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('entry', models.DateField()),
                ('exit', models.DateField()),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
